<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class RayonSeeder extends Seeder
{
    public function run()
    {
        $records = [
            [
                'PositionID' => 'BTMAESA01011',
                'EmployeePosition' => 'MR',
                'CompanyID' => 'IBT',
                'AreaID' => 'BTM',
                'AreaBaseID' => 'BATAM',
                'AreaFF' => 'BATAM',
                'RayonID' => 'BATAM',
                'LineID' => 'AESTHETIC',
                'LineBaseID' => 'BATAM',
                'LinePositionFF' => 'AESTHETIC',
                'AmPos' => 'BTMAESSA0101',
                'RmPos' => 'BTMAESRMA01',
                'SMPos' => null,
                'NSMPos' => 'NSMAESIBTA01',
                'MMPos' => 'MMAESIBTA001',
                'GMPos' => 'GMREGMA0001',
                'MDPos' => 'MDREGMA0003',
                'Station' => 'N',
                'StartDate' => '2021-01-01 00:00:00.000',
                'EndDate' => '4009-12-31 00:00:00.000',
                'PositionStatus' => 'A',
                'UserID' => 'system',
                'LastUpdate' => '2021-01-20 15:12:41.880',
                'AreaGroupID' => 'BTM',
            ],
            [
                'PositionID' => 'BTMAESRMA01',
                'EmployeePosition' => 'RM',
                'CompanyID' => 'IBT',
                'AreaID' => 'BTM',
                'AreaBaseID' => 'BATAM',
                'AreaFF' => 'BATAM',
                'RayonID' => 'BATAM',
                'LineID' => 'AESTHETIC',
                'LineBaseID' => 'BATAM',
                'LinePositionFF' => 'N/A',
                'AmPos' => 'N/A',
                'RmPos' => null,
                'SMPos' => null,
                'NSMPos' => 'NSMAESIBTA01',
                'MMPos' => 'MMAESIBTA001',
                'GMPos' => 'GMREGMA0001',
                'MDPos' => 'MDREGMA0003',
                'Station' => 'N',
                'StartDate' => '2021-01-01 00:00:00.000',
                'EndDate' => '4009-12-31 00:00:00.000',
                'PositionStatus' => 'A',
                'UserID' => 'system',
                'LastUpdate' => '2021-01-20 15:12:41.893',
                'AreaGroupID' => 'BTM',
            ],
            [
                'PositionID' => 'BTMAESSA0101',
                'EmployeePosition' => 'AM',
                'CompanyID' => 'IBT',
                'AreaID' => 'BTM',
                'AreaBaseID' => 'BATAM',
                'AreaFF' => 'BATAM',
                'RayonID' => 'BATAM',
                'LineID' => 'AESTHETIC',
                'LineBaseID' => 'BATAM',
                'LinePositionFF' => 'N/A',
                'AmPos' => 'BTMAESRMA01',
                'RmPos' => null,
                'SMPos' => null,
                'NSMPos' => 'NSMAESIBTA01',
                'MMPos' => 'MMAESIBTA001',
                'GMPos' => 'GMREGMA0001',
                'MDPos' => 'MDREGMA0003',
                'Station' => 'N',
                'StartDate' => '2021-01-01 00:00:00.000',
                'EndDate' => '4009-12-31 00:00:00.000',
                'PositionStatus' => 'A',
                'UserID' => 'system',
                'LastUpdate' => '2021-01-20 15:12:41.890',
                'AreaGroupID' => 'BTM',
            ],
            [
                'PositionID' => 'BTMOGBIBTSN1',
                'EmployeePosition' => 'AM',
                'CompanyID' => 'IBT',
                'AreaID' => 'BTM',
                'AreaBaseID' => 'BATAM',
                'AreaFF' => 'BATAM',
                'RayonID' => 'BATAM',
                'LineID' => 'OGB',
                'LineBaseID' => 'BATAM',
                'LinePositionFF' => 'N/A',
                'AmPos' => 'JKTOGBRMA01',
                'RmPos' => null,
                'SMPos' => null,
                'NSMPos' => 'NSMOGBIBTA01',
                'MMPos' => 'MMOGBIBTMA01',
                'GMPos' => 'GMOGBMA0001',
                'MDPos' => 'MDREGMA0003',
                'Station' => 'N',
                'StartDate' => '2023-02-01 00:00:00.000',
                'EndDate' => '4009-12-31 00:00:00.000',
                'PositionStatus' => 'A',
                'UserID' => 'systemOGB',
                'LastUpdate' => '2023-02-10 14:50:37.860',
                'AreaGroupID' => 'BTM',
            ],
            [
                'PositionID' => 'BTMREGB35011',
                'EmployeePosition' => 'MR',
                'CompanyID' => 'IBT',
                'AreaID' => 'BTM',
                'AreaBaseID' => 'RS. Otorita Batam',
                'AreaFF' => 'BATAM',
                'RayonID' => 'BATAM',
                'LineID' => 'ETHICAL',
                'LineBaseID' => 'BATAM',
                'LinePositionFF' => 'BTMREGSB3501',
                'AmPos' => 'BTMREGRMB11',
                'RmPos' => null,
                'SMPos' => null,
                'NSMPos' => 'NSMREGL00001',
                'MMPos' => 'MMREGMB00001',
                'GMPos' => 'GMREGMA0001',
                'MDPos' => 'MDREGMA0001',
                'Station' => 'N',
                'StartDate' => '2022-01-01 00:00:00.000',
                'EndDate' => '4009-12-31 00:00:00.000',
                'PositionStatus' => 'A',
                'UserID' => 'limjin',
                'LastUpdate' => '2022-01-06 14:40:08.330',
                'AreaGroupID' => 'BTM',
            ],
            [
                'PositionID' => 'BTMREGB35012',
                'EmployeePosition' => 'MR',
                'CompanyID' => 'IBT',
                'AreaID' => 'BTM',
                'AreaBaseID' => 'RS. Santa Elisabeth + Natuna',
                'AreaFF' => 'BATAM',
                'RayonID' => 'BATAM',
                'LineID' => 'ETHICAL',
                'LineBaseID' => 'BATAM',
                'LinePositionFF' => 'BTMREGSB3501',
                'AmPos' => 'BTMREGRMB11',
                'RmPos' => null,
                'SMPos' => null,
                'NSMPos' => 'NSMREGL00001',
                'MMPos' => 'MMREGMB00001',
                'GMPos' => 'GMREGMA0001',
                'MDPos' => 'MDREGMA0001',
                'Station' => 'N',
                'StartDate' => '2022-01-01 00:00:00.000',
                'EndDate' => '4009-12-31 00:00:00.000',
                'PositionStatus' => 'A',
                'UserID' => 'limjin',
                'LastUpdate' => '2022-01-06 14:40:08.330',
                'AreaGroupID' => 'BTM',
            ],
            [
                'PositionID' => 'BTMREGB35021',
                'EmployeePosition' => 'MR',
                'CompanyID' => 'IBT',
                'AreaID' => 'BTM',
                'AreaBaseID' => 'RS. Budi Kemuliaan',
                'AreaFF' => 'BATAM',
                'RayonID' => 'BATAM',
                'LineID' => 'ETHICAL',
                'LineBaseID' => 'BATAM',
                'LinePositionFF' => 'BTMREGSB3502',
                'AmPos' => 'BTMREGRMB11',
                'RmPos' => null,
                'SMPos' => null,
                'NSMPos' => 'NSMREGL00001',
                'MMPos' => 'MMREGMB00001',
                'GMPos' => 'GMREGMA0001',
                'MDPos' => 'MDREGMA0001',
                'Station' => 'N',
                'StartDate' => '2022-01-01 00:00:00.000',
                'EndDate' => '4009-12-31 00:00:00.000',
                'PositionStatus' => 'A',
                'UserID' => 'limjin',
                'LastUpdate' => '2022-01-06 14:40:08.330',
                'AreaGroupID' => 'BTM',
            ],
            [
                'PositionID' => 'BTMREGB35022',
                'EmployeePosition' => 'MR',
                'CompanyID' => 'IBT',
                'AreaID' => 'BTM',
                'AreaBaseID' => 'RS. Awal Bros + TBK + Batu aji',
                'AreaFF' => 'BATAM',
                'RayonID' => 'BATAM',
                'LineID' => 'ETHICAL',
                'LineBaseID' => 'BATAM',
                'LinePositionFF' => 'BTMREGSB3502',
                'AmPos' => 'BTMREGRMB11',
                'RmPos' => null,
                'SMPos' => null,
                'NSMPos' => 'NSMREGL00001',
                'MMPos' => 'MMREGMB00001',
                'GMPos' => 'GMREGMA0001',
                'MDPos' => 'MDREGMA0001',
                'Station' => 'N',
                'StartDate' => '2022-01-01 00:00:00.000',
                'EndDate' => '4009-12-31 00:00:00.000',
                'PositionStatus' => 'A',
                'UserID' => 'limjin',
                'LastUpdate' => '2022-01-06 14:40:08.330',
                'AreaGroupID' => 'BTM',
            ],
            [
                'PositionID' => 'BTMREGB35031',
                'EmployeePosition' => 'MR',
                'CompanyID' => 'IBT',
                'AreaID' => 'BTM',
                'AreaBaseID' => 'RS. Budi Kemuliaan',
                'AreaFF' => 'BATAM',
                'RayonID' => 'BATAM',
                'LineID' => 'ETHICAL',
                'LineBaseID' => 'BATAM',
                'LinePositionFF' => 'BTMREGSB3503',
                'AmPos' => 'BTMREGRMB11',
                'RmPos' => null,
                'SMPos' => null,
                'NSMPos' => 'NSMREGL00001',
                'MMPos' => 'MMREGMB00001',
                'GMPos' => 'GMREGMA0001',
                'MDPos' => 'MDREGMA0001',
                'Station' => 'N',
                'StartDate' => '2022-01-01 00:00:00.000',
                'EndDate' => '4009-12-31 00:00:00.000',
                'PositionStatus' => 'A',
                'UserID' => 'system',
                'LastUpdate' => '2022-01-06 14:40:08.330',
                'AreaGroupID' => 'BTM',
            ],
            [
                'PositionID' => 'BTMREGB35032',
                'EmployeePosition' => 'MR',
                'CompanyID' => 'IBT',
                'AreaID' => 'BTM',
                'AreaBaseID' => 'RS. Awal Bros + TBK + Batu aji',
                'AreaFF' => 'BATAM',
                'RayonID' => 'BATAM',
                'LineID' => 'ETHICAL',
                'LineBaseID' => 'BATAM',
                'LinePositionFF' => 'BTMREGSB3503',
                'AmPos' => 'BTMREGRMB11',
                'RmPos' => null,
                'SMPos' => null,
                'NSMPos' => 'NSMREGL00001',
                'MMPos' => 'MMREGMB00001',
                'GMPos' => 'GMREGMA0001',
                'MDPos' => 'MDREGMA0001',
                'Station' => 'N',
                'StartDate' => '2022-01-01 00:00:00.000',
                'EndDate' => '4009-12-31 00:00:00.000',
                'PositionStatus' => 'A',
                'UserID' => 'system',
                'LastUpdate' => '2022-01-06 14:40:08.330',
                'AreaGroupID' => 'BTM',
            ],
            [
                'PositionID' => 'BTMREGB35041',
                'EmployeePosition' => 'MR',
                'CompanyID' => 'IBT',
                'AreaID' => 'BTM',
                'AreaBaseID' => 'RS. Budi Kemuliaan',
                'AreaFF' => 'BATAM',
                'RayonID' => 'BATAM',
                'LineID' => 'ETHICAL',
                'LineBaseID' => 'BATAM',
                'LinePositionFF' => 'BTMREGSB3504',
                'AmPos' => 'BTMREGRMB11',
                'RmPos' => null,
                'SMPos' => null,
                'NSMPos' => 'NSMREGL00001',
                'MMPos' => 'MMREGMB00001',
                'GMPos' => 'GMREGMA0001',
                'MDPos' => 'MDREGMA0001',
                'Station' => 'N',
                'StartDate' => '2022-01-01 00:00:00.000',
                'EndDate' => '4009-12-31 00:00:00.000',
                'PositionStatus' => 'A',
                'UserID' => 'system',
                'LastUpdate' => '2022-01-06 14:40:08.330',
                'AreaGroupID' => 'BTM',
            ],
            [
                'PositionID' => 'BTMREGB35042',
                'EmployeePosition' => 'MR',
                'CompanyID' => 'IBT',
                'AreaID' => 'BTM',
                'AreaBaseID' => 'RS. Awal Bros + TBK + Batu aji',
                'AreaFF' => 'BATAM',
                'RayonID' => 'BATAM',
                'LineID' => 'ETHICAL',
                'LineBaseID' => 'BATAM',
                'LinePositionFF' => 'BTMREGSB3504',
                'AmPos' => 'BTMREGRMB11',
                'RmPos' => null,
                'SMPos' => null,
                'NSMPos' => 'NSMREGL00001',
                'MMPos' => 'MMREGMB00001',
                'GMPos' => 'GMREGMA0001',
                'MDPos' => 'MDREGMA0001',
                'Station' => 'N',
                'StartDate' => '2022-01-01 00:00:00.000',
                'EndDate' => '4009-12-31 00:00:00.000',
                'PositionStatus' => 'A',
                'UserID' => 'system',
                'LastUpdate' => '2022-01-06 14:40:08.330',
                'AreaGroupID' => 'BTM',
            ],
        ];

        DB::table('Position_Structure_IBT')->insert($records);
    }
}
